spring:
  thymeleaf:
    # 关闭缓存
    cache: false
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456789qw
    hikari:
      # 连接池名字
      pool-name: DateHikariCP
      # 最小连接数
      minimum-idle: 5
      # 空闲连接最大存活时间10分钟
      idle-timeout: 1800000
      # 最大连接数，默认为10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间， 默认是半小时
      max-lifetime: 1800000
      # 连接超时时间，默认30秒
      connection-timeout: 30000
      # 心跳机制，测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  redis:
    host: 192.168.2.219
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        # 最大空闲连接，默认8
        max-idle: 8
        min-idle: 5
# mybatis-plus配置
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置MyBatis数据返回类型别名
  type-aliases-package: com.xxx.seckill.pojo

# Mybatis SQL打印（方法接口所在的包，不是mapper.xml所在的包）
logging:
  level:
    com.xxx.seckill.mapper: debug
